version: "3.0" # version of docker-compose

services: # list of services we want to run as part of our application

  nginx: # name of the service, it will automatically become a network alias | "--network-alias" option with docker run

    build: ./requirements/nginx # location of the Dockerfile used to build the service
    ports:
      - "443:443" # binds the host port 3000 to the published container port 3000 (HOST:CONTAINER) | "-p 3000:3000" option with docker run
    volumes:
      - wp_volume:/var/www/html # maps the volume HOST:CONTAINER | "-v host_volume:container_volume" option with docker run
    networks:
      - inception
    restart: always # restart the service if it crashes
    depends_on:
      - wordpress
    container_name: nginx

  wordpress:
    build: ./requirements/wordpress
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
    container_name: wordpress

  mariadb:
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception
    restart: always
    container_name: mariadb

networks:
  inception: # create a network inception for the containers on this network to communicate | equivalent to docker network create inception command

volumes:
  wp_volume:
    driver:
      - local
    driver_opts:
      type: none
      o: bind
      device: /home/rlinkov/data/wp_volume # Linux VM
      # device:../volumes/wp_volume #MacOS
  dp_volume:
    driver:
      - local
    driver_opts:
      type: none
      o: bind
      device: /home/rlinkov/data/db_volume #Linux VM
      # device: ../volumes/db_volume # MacOS

# run with docker-compose up -d | -d option to run it in the background
# docker-compose create a default network for the application
# docker-compose build to rebuild image after altering Dockerfile